name: "mmseqs_easytaxonomy"
description: Searches for the taxonomy of sequences of a fasta file in a database using MMseqs2
keywords:
  - protein sequence
  - databases
  - searching
  - mmseqs2
tools:
  - "mmseqs":
      description: "MMseqs2: ultra fast and sensitive sequence search and clustering
        suite"
      homepage: "https://github.com/soedinglab/MMseqs2"
      documentation: "https://mmseqs.com/latest/userguide.pdf"
      tool_dev_url: "https://github.com/soedinglab/MMseqs2"
      doi: "10.1093/bioinformatics/btw006"
      licence: ["GPL v3"]
      identifier: biotools:mmseqs
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing input fasta file information
          e.g. `[ id:'test' ]`
    - fasta:
        type: file
        description: Fasta file
        pattern: "*.{fa,fasta}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing database information
          e.g. `[ id:'test' ]`
    - db_target:
        type: directory
        description: an MMseqs2 database with target data, e.g. uniref90
output:
  - lca:
      - meta:
          type: map
          description: |
            Groovy Map containing input fasta file information
            e.g. `[ id:'test']`
      - ${prefix}_lca.tsv:
          type: file
          description: tsv file with the results of the taxonomy search
          pattern: "*_lca.{tsv}"
  - report:
      - meta:
          type: map
          description: |
            Groovy Map containing input fasta file information
            e.g. `[ id:'test']`
      - ${prefix}_report:
          type: file
          description: file with other results of the taxonomy search
          pattern: "*_report"
  - tophit_aln:
      - meta:
          type: map
          description: |
            Groovy Map containing input fasta file information
            e.g. `[ id:'test']`
      - ${prefix}_tophit_aln:
          type: file
          description: file with so other results of the taxonomy search
          pattern: "*_tophit_aln"
  - tophit_report:
      - meta:
          type: map
          description: |
            Groovy Map containing input fasta file information
            e.g. `[ id:'test']`
      - ${prefix}_tophit_report:
          type: file
          description: file with so other report of the results of the taxonomy search
          pattern: "*_tophit_report"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
  - "@unholyparrot"
maintainers:
  - "@luisas"
  - "@unholyparrot"